---
#    config-sync
#    no shut
#    end
- hosts: LOCALHOST

  tasks:
    - name: configsync no shut
      uri:
         url:              "http://{{ ANSIBLE_VMR_IP }}:{{ ANSIBLE_VMR_SEMP_PORT }}/SEMP"
         method:           GET
         user:             "{{ ANSIBLE_USERNAME }}"
         password:         "{{ ANSIBLE_PASSWORD }}"
         body:             "<rpc semp-version='soltr/8_2VMR'>\
                           <config-sync><no><shutdown/></no></config-sync></rpc>"
         force_basic_auth: yes
         status_code:      200
         body_format:      raw
         return_content:   yes
      register: rpc_reply
      ignore_errors: True
      until: rpc_reply|success
      retries: 60
      delay: 10