---
#    active-standby-role primary
#    mate-link connect-via 192.168.169.101

- hosts: LOCALHOST
  vars:
     VMR_ROLE: "{{ lookup('env', 'VMR_ROLE') }}"
     MATE_IP: "{{ lookup('env', 'MATE_IP') }}"

  tasks:
    - name: Redundancy active-standby role
      uri:
         url:              "http://{{ ANSIBLE_VMR_IP }}:{{ ANSIBLE_VMR_SEMP_PORT }}/SEMP"
         method:           GET
         user:             "{{ ANSIBLE_USERNAME }}"
         password:         "{{ ANSIBLE_PASSWORD }}"
         body:             "<rpc semp-version='soltr/8_2VMR'>\
                           <redundancy><active-standby-role><{{ VMR_ROLE }}/></active-standby-role></redundancy></rpc>"
         force_basic_auth: yes
         status_code:      200
         body_format:      raw
         return_content:   yes
      register: rpc_reply
      ignore_errors: True
      until: rpc_reply|success
      retries: 60
      delay: 10

    - name: Redundancy mate-link
      uri:
         url:              "http://{{ ANSIBLE_VMR_IP }}:{{ ANSIBLE_VMR_SEMP_PORT }}/SEMP"
         method:           GET
         user:             "{{ ANSIBLE_USERNAME }}"
         password:         "{{ ANSIBLE_PASSWORD }}"
         body:             "<rpc semp-version='soltr/8_2VMR'>\
                           <redundancy><mate-link><connect-via><hostname-or-address>{{ MATE_IP }}</hostname-or-address></connect-via></mate-link></redundancy></rpc>"
         force_basic_auth: yes
         status_code:      200
         body_format:      raw
         return_content:   yes
      register: rpc_reply
      ignore_errors: True
      until: rpc_reply|success
      retries: 60
      delay: 10